"""
Pydantic models for the POST /chat endpoint (Dialogflow CX proxy).
"""


from pydantic import BaseModel, field_validator


class ChatRequest(BaseModel):
    """Request body for POST /api/v1/chat."""

    message: str
    session_id: str          # UUID v4 generated by the frontend on component mount
    country: str | None = None
    language_code: str = "en"

    @field_validator("message")
    @classmethod
    def validate_message(cls, v: str) -> str:
        v = v.strip()
        if len(v) < 1:
            raise ValueError("message must not be empty")
        if len(v) > 500:
            raise ValueError("message must not exceed 500 characters")
        return v


class ChatResponse(BaseModel):
    """Response body for POST /api/v1/chat."""

    reply: str
    intent: str | None = None          # Dialogflow matched intent display name; null if undetermined
    session_id: str                        # Echoed back so the frontend can correlate responses
    suggested_topics: list[str] = []      # List of topic slugs suggested by the assistant
